import { constants } from './constants.js'

let games = [
  {
    id: '1',
    title: 'The Elder Scrolls V: Skyrim',
    description: 'The Elder Scrolls V: Skyrim is an action role-playing game developed by Bethesda Game Studios. Released in 2011, it is the fifth main installment in the Elder Scrolls series. The game is set in the fictional province of Skyrim, in the frozen wilderness of the Tamriel continent. Players take on the role of the Dragonborn, a hero born with the power to absorb the souls of dragons and use their abilities. The game features an enormous open world, allowing players to explore, complete quests, master magical spells, and engage in combat with various enemies, including the legendary dragons. Skyrim has been released on multiple platforms, including PC, PS4, Xbox One, Nintendo Switch, Xbox 360, PS3, and even VR, ensuring its enduring popularity.',
    platform: ['PC', 'PS4', 'Xbox One', 'Nintendo Switch', 'Xbox 360', 'PS3', 'VR'],
    price: 19.99,
    genre: ['Action', 'RPG', 'Adventure'],
    isAdminLiked: true,
    image: 'https://i.ibb.co/TK7SpV6/the-elder-scrolls-v-skyrim.webp'
  },
  {
    id: '2',
    title: 'Minecraft',
    description: 'Minecraft is a sandbox video game developed by Mojang Studios. First released in 2011, it has become one of the most popular and influential games of all time. Players are dropped into a procedurally generated world made up of blocks, which can be mined for resources such as wood, stone, and minerals. The game offers various modes, including Creative, Survival, and Hardcore, each providing a unique experience. In Survival mode, players must gather resources, build structures, and fend off hostile mobs that come out at night. Minecraft’s creative freedom and educational value have made it a favorite among both children and adults, available on a wide range of platforms including PC, PS4, Xbox One, Nintendo Switch, PS3, Xbox 360, iOS, Android, and PS Vita.',
    platform: ['PC', 'PS4', 'Xbox One', 'Nintendo Switch', 'PS3', 'Xbox 360', 'iOS', 'Android', 'PS Vita'],
    price: 29.99,
    genre: ['Sandbox', 'Survival', 'Adventure'],
    isAdminLiked: false,
    image: 'https://i.ibb.co/XXqfnTb/pixlr-image-generator-3d9f8b96-41db-41e3-af1b-6b0f42f4c9ca.webp'
  },
  {
    id: '3',
    title: 'Batman: Arkham Knight',
    description: 'Batman: Arkham Knight is an action-adventure game developed by Rocksteady Studios and released in 2015. It is the final installment in the Batman: Arkham series and follows Batman as he faces off against the Scarecrow and other villains in Gotham City. The game introduces the Batmobile as a central gameplay mechanic, allowing players to drive and engage in combat with the vehicle. The game features a large open world, improved combat mechanics, and a rich narrative that concludes the Arkham series. Available on PC, PS4, and Xbox One, Arkham Knight is praised for its engaging storyline, advanced graphics, and immersive gameplay.',
    platform: ['PC', 'PS4', 'Xbox One'],
    price: 24.99,
    genre: ['Action', 'Adventure'],
    isAdminLiked: false,
    image: 'https://i.ibb.co/Xk21bHG/batman-arkham-knight.webp'
  },
  {
    id: '4',
    title: 'Doom',
    description: 'Doom is a first-person shooter game developed by id Software and released in 2016. It is a reboot of the classic Doom series and returns to the fast-paced, action-packed gameplay that defined the originals. Players take on the role of the Doom Marine, fighting against hordes of demons from Hell that have invaded Mars. The game is known for its intense combat, fast movement, and the ability to execute gruesome finishing moves called "glory kills." Available on PC, PS4, Xbox One, and Nintendo Switch, Doom has been praised for its high-energy gameplay and faithful return to the series’ roots.',
    platform: ['PC', 'PS4', 'Xbox One', 'Nintendo Switch'],
    price: 18.99,
    genre: ['First-Person Shooter', 'Action'],
    isAdminLiked: true,
    image: 'https://i.ibb.co/Y3P2Bfm/doom.webp'
  },
  {
    id: '5',
    title: 'PUBG: BATTLEGROUNDS',
    description: 'PUBG: BATTLEGROUNDS is a battle royale game developed by PUBG Corporation. In this game, 100 players are dropped from a plane onto an 8km x 8km map, where they must scavenge for weapons, armor, and other supplies to survive. The game features a shrinking play area, known as the "Blue Zone," which forces players to move closer together, increasing the intensity of encounters. Players can choose to play solo, in duos, or in squads of up to four players. The game is known for its realistic gameplay, large maps, and strategic depth, requiring players to manage resources, use vehicles, and employ tactical skills to be the last one or team standing. PUBG: BATTLEGROUNDS is available on multiple platforms, including PC, PS4, Xbox One, Android, and iOS.',
    platform: ['PC', 'PS4', 'Xbox One', 'Android', 'iOS'],
    price: 14.99,
    genre: ['Battle Royale', 'Survival', 'Action'],
    isAdminLiked: true,
    image: 'https://i.ibb.co/hFvwGyg/pubg.webp'
  },
  {
    id: '6',
    title: 'Rocket League',
    description: 'Rocket League is a physics-based sports game developed by Psyonix and released in 2015. The game combines elements of soccer with high-speed vehicles, where players control cars and try to score goals in a soccer-like game. Known for its addictive gameplay and strong focus on multiplayer, Rocket League requires a combination of driving skills and teamwork to succeed. Available on PC, PlayStation 4, Xbox One, and other platforms, it has become a favorite among gamers for its unique blend of sports and racing.',
    platform: ['PC', 'PlayStation 4', 'Xbox One'],
    price: 19.59,
    genre: ['Sports', 'Racing', 'Multiplayer'],
    isAdminLiked: false,
    image: 'https://i.ibb.co/5cxM8SH/rocket-league.webp'
  },
  {
    id: '7',
    title: 'Assassin’s Creed IV: Black Flag',
    description: 'Assassin’s Creed IV: Black Flag is an action-adventure game developed by Ubisoft and released in 2013. Set in the early 18th century, the game follows the story of Edward Kenway, a pirate and the grandfather of Connor Kenway from Assassin’s Creed III. Players explore the open seas, engage in naval combat, and interact with historical figures. The game is praised for its historical authenticity, engaging storyline, and the freedom to explore the Caribbean seas. Available on PC, PlayStation 4, Xbox One, and other platforms.',
    platform: ['PC', 'PlayStation 4', 'Xbox One'],
    price: 24.99,
    genre: ['Action', 'Adventure', 'Historical'],
    isAdminLiked: false,
    image: 'https://i.ibb.co/D53n9x7/assassins-creed.webp'
  },
  {
    id: '8',
    title: 'Counter-Strike 2',
    description: 'Counter-Strike 2 is a multiplayer tactical first-person shooter developed by Valve Corporation. Released in 2023, it is the successor to Counter-Strike: Global Offensive. The game pits two teams, the Counter-Terrorists and the Terrorists, against each other in various objective-based game modes. The primary game modes include Competitive and Premier, where teams compete to complete objectives such as defusing bombs or rescuing hostages. The game features significant technical improvements, including a move to the Source 2 engine, enhanced graphics, and new gameplay mechanics like volumetric smoke physics. Players can purchase weapons and equipment between rounds, and the game emphasizes strategic team play and quick reflexes. Available on PC, Counter-Strike 2 offers a fast-paced and responsive gameplay experience.',
    platform: ['PC'],
    price: 0.00,
    genre: ['First-Person Shooter', 'Tactical', 'Multiplayer'],
    isAdminLiked: true,
    image: 'https://i.ibb.co/8BzqDqM/cs2.webp'
  },
  {
    id: '9',
    title: 'The Sims',
    description: 'The Sims is a life simulation game developed by Maxis and published by Electronic Arts, first released in 2000. Players create and control virtual characters, known as Sims, and manage their daily lives, including building homes, forming relationships, and pursuing careers. The game offers a sandbox experience where players can explore various aspects of life in a virtual world. With its addictive gameplay and endless possibilities, The Sims has become one of the most successful and influential game series of all time, available on PC, PlayStation 2, Xbox, and other platforms.',
    platform: ['PC', 'PlayStation 2', 'Xbox'],
    price: 29.49,
    genre: ['Life Simulation', 'Sandbox'],
    isAdminLiked: false,
    image: 'https://i.ibb.co/XFbY6DZ/sims.webp'
  },
  {
    id: '10',
    title: 'Dota 2',
    description: 'Dota 2 is a multiplayer online battle arena (MOBA) game developed and published by Valve Corporation, released in 2013. Players control a hero with unique abilities and battle against another team in a strategic and competitive environment. The game is known for its deep strategic gameplay, a vast array of heroes and items, and regular updates that add new characters and balance changes. Dota 2 is one of the most popular games in the MOBA genre and a major player in the esports scene, available exclusively on PC.',
    platform: ['PC'],
    price: 0.00,
    genre: ['Strategy', 'Multiplayer'],
    isAdminLiked: false,
    image: 'https://i.ibb.co/F5cMgGw/dota2.webp'
  },
  {
    id: '11',
    title: 'Metal Gear Solid V: The Phantom Pain',
    description: 'Metal Gear Solid V: The Phantom Pain is an action-adventure game developed by Kojima Productions and published by Konami, released in 2015. The game follows the story of Big Boss (also known as Venom Snake) as he builds a private military company in the 1980s. Known for its open-world design, complex storyline, and innovative gameplay mechanics, The Phantom Pain is the final main installment in the Metal Gear Solid series. Available on PC, PlayStation 4, Xbox One, and other platforms, it has received critical acclaim for its storytelling and gameplay.',
    platform: ['PC', 'PlayStation 4', 'Xbox One'],
    price: 24.99,
    genre: ['Action', 'Adventure', 'Stealth'],
    isAdminLiked: true,
    image: 'https://i.ibb.co/FbmHmbh/metal-gear-solid.webp'
  },
  {
    id: '12',
    title: 'System Shock 2',
    description: 'System Shock 2 is a first-person role-playing game with elements of horror, developed by Irrational Games and Looking Glass Studios, released in 1999. The game is set in a dystopian future where players must navigate a spaceship overrun by mutants and an artificial intelligence known as SHODAN. Known for its engaging storyline, challenging gameplay, and atmospheric setting, System Shock 2 has become a cult classic and is still remembered fondly by many gamers. Available on PC and Dreamcast.',
    platform: ['PC', 'Dreamcast'],
    price: 8.99,
    genre: ['RPG', 'First-Person Shooter', 'Horror'],
    isAdminLiked: true,
    image: 'https://i.ibb.co/TvkvQ5P/system-shock2.webp'
  }
];

let users = [
  { id: '1', username: 'Ivan Ivanov', verified: true, avatar: 'https://i.ibb.co/zf3JN7j/1.webp' },
  { id: '2', username: 'killer1408', verified: false, avatar: 'https://i.ibb.co/m9XW0Mm/2.webp' },
  { id: '3', username: 'Maria Petrova', verified: true, avatar: 'https://i.ibb.co/SNvwXP8/3.webp' },
  { id: '4', username: 'hunter', verified: false, avatar: 'https://i.ibb.co/CJg4zqH/4.webp' },
  { id: '5', username: 'Sergey Kuznetsov', verified: true, avatar: 'https://i.ibb.co/3YmkwHT/5.webp' },
  { id: '6', username: 'ghost', verified: false, avatar: 'https://i.ibb.co/3pw8Z6x/6.webp' },
  { id: '7', username: 'Olga Sokolova', verified: true, avatar: 'https://i.ibb.co/p1QMWcc/7.webp' },
  { id: '8', username: 'CREEP', verified: false, avatar: 'https://i.ibb.co/BGys4g3/8.webp' },
  { id: '9', username: 'Natalia Ivanova', verified: true, avatar: 'https://i.ibb.co/s5WvQDQ/9.webp' },
  { id: '10', username: 'NinjaAssassin', verified: false, avatar: 'https://i.ibb.co/K5bVSqF/10.webp' },
  { id: '11', username: 'Elena Kuznetsova', verified: true, avatar: 'https://i.ibb.co/VN0k73g/11.webp' },
  { id: '12', username: 'Frostbite', verified: false, avatar: 'https://i.ibb.co/5BV2kqD/12.webp' },
  { id: '13', username: 'Tatiana Petrova', verified: true, avatar: 'https://i.ibb.co/pZsyBH5/13.webp' },
  { id: '14', username: 'ShadowStriker', verified: false, avatar: 'https://i.ibb.co/kgQK7B8/14.webp' },
  { id: '15', username: 'Anastasia Sokolova', verified: true, avatar: 'https://i.ibb.co/L5rm6hh/15.webp' },
  { id: '16', username: 'Viper', verified: false, avatar: 'https://i.ibb.co/tLhnhHm/16.webp' },
  { id: '17', username: 'Ekaterina Ivanova', verified: true, avatar: 'https://i.ibb.co/s2r9LJG/17.webp' },
  { id: '18', username: 'DarkKnight', verified: false, avatar: 'https://i.ibb.co/YkRRjHS/18.webp' },
  { id: '19', username: 'Anna Kuznetsova', verified: true, avatar: 'https://i.ibb.co/R26jWCY/19.webp' },
  { id: '20', username: 'Phantom', verified: false, avatar: 'https://i.ibb.co/CJ0rJgk/20.webp' },
  { id: '21', username: 'Victoria Petrova', verified: true, avatar: 'https://i.ibb.co/KhGHkwK/21.webp' },
  { id: '22', username: 'Warlock', verified: false, avatar: 'https://i.ibb.co/GxsVz1z/22.webp' },
  { id: '23', username: 'Sofia Sokolova', verified: true, avatar: 'https://i.ibb.co/tCVn3ZS/23.webp' },
  { id: '24', username: 'Reaper', verified: false, avatar: 'https://i.ibb.co/YZSWwyZ/24.webp' },
  { id: '25', username: 'Alex Hunter', verified: true, avatar: 'https://i.ibb.co/VCZGF5M/25.webp' },
  { id: '26', username: 'VengefulSpirit', verified: false, avatar: 'https://i.ibb.co/NywS0yt/26.webp' },
  { id: '27', username: 'Max TOP AWP', verified: true, avatar: 'https://i.ibb.co/SyRjz4p/27.webp' },
  { id: '28', username: 'DragonFly', verified: false, avatar: 'https://i.ibb.co/NZdN7Lg/28.webp' },
  { id: '29', username: 'Ivan Pro', verified: true, avatar: 'https://i.ibb.co/rMb6VFB/29.webp' },
  { id: '30', username: 'ShadowWalker', verified: false, avatar: 'https://i.ibb.co/1Ljnf2Z/30.webp' },
  { id: '31', username: 'Sergey Ninja', verified: true, avatar: 'https://i.ibb.co/Q9Ykyqs/31.webp' },
  { id: '32', username: 'DarkPhoenix', verified: false, avatar: 'https://i.ibb.co/zQ8N5Fg/32.webp' },
  { id: '33', username: 'Michael Mage', verified: true, avatar: 'https://i.ibb.co/jgStTFQ/33.webp' },
  { id: '34', username: 'Natalia Archer', verified: false, avatar: 'https://i.ibb.co/zn84mGc/34.webp' },
  { id: '35', username: 'James Rogue', verified: true, avatar: 'https://i.ibb.co/CV59njx/35.webp' },
  { id: '36', username: 'StormBringer', verified: false, avatar: 'https://i.ibb.co/SVjbDfz/36.webp' },
  { id: '37', username: 'Robert Tank', verified: true, avatar: 'https://i.ibb.co/XxQ9m4S/37.webp' },
  { id: '38', username: 'Anastasia Assassin', verified: false, avatar: 'https://i.ibb.co/BwXrP1d/38.webp' },
  { id: '39', username: 'Richard Paladin', verified: true, avatar: 'https://i.ibb.co/B3DdNqr/39.webp' },
  { id: '40', username: 'Ekaterina Druid', verified: false, avatar: 'https://i.ibb.co/McyK2F9/40.webp' },
  { id: '41', username: 'Charles Shaman', verified: true, avatar: 'https://i.ibb.co/TtmM1F5/41.webp' },
  { id: '42', username: 'Anna Bard', verified: false, avatar: 'https://i.ibb.co/5kZZrSN/42.webp' },
  { id: '43', username: 'Joseph Warlock', verified: true, avatar: 'https://i.ibb.co/DQNSn7V/43.webp' },
  { id: '44', username: 'Victoria Monk', verified: false, avatar: 'https://i.ibb.co/2K0LZyW/44.webp' },
  { id: '45', username: 'Thomas Priest', verified: true, avatar: 'https://i.ibb.co/SvZJgTg/45.webp' },
  { id: '46', username: 'Sofia DeathKnight', verified: false, avatar: 'https://i.ibb.co/wCRgR0D/46.webp' },
  { id: '47', username: 'Christopher DemonHunter', verified: true, avatar: 'https://i.ibb.co/2N2R8J4/47.webp' },
  { id: '48', username: 'Alex Hunter', verified: false, avatar: 'https://i.ibb.co/LSNGVdS/48.webp' },
  { id: constants.adminId , username: 'ADMIN', verified: true, avatar: 'https://i.ibb.co/NLBsZqr/ADMIN.webp' },
];


let reviews = [
  { id: '1', rating: 5, content: 'Amazing game!', user_id: '1', game_id: '1' },
  { id: '2', rating: 4, content: 'Great gameplay, some bugs.', user_id: '2', game_id: '1' },
  { id: '3', rating: 5, content: 'Лучшая игра, которую я когда-либо играл!', user_id: '3', game_id: '2' },
  { id: '4', rating: 3, content: 'It\'s okay, but not my favorite.', user_id: '4', game_id: '2' },
  { id: '5', rating: 5, content: 'This game is so much fun!', user_id: '5', game_id: '3' },
  { id: '6', rating: 4, content: 'Good game, but the puzzles are hard.', user_id: '6', game_id: '3' },
  { id: '7', rating: 5, content: 'Игра просто супер!', user_id: '7', game_id: '4' },
  { id: '8', rating: 4, content: 'Great game for kids and adults.', user_id: '8', game_id: '4' },
  { id: '9', rating: 5, content: 'One of the best games ever made.', user_id: '9', game_id: '5' },
  { id: '10', rating: 4, content: 'Good storyline, but some glitches.', user_id: '10', game_id: '5' },
  { id: '11', rating: 5, content: 'Love the graphics!', user_id: '11', game_id: '1' },
  { id: '12', rating: 3, content: 'Not bad, but could be better.', user_id: '12', game_id: '1' },
  { id: '13', rating: 5, content: 'Очень крутая игра!', user_id: '13', game_id: '2' },
  { id: '14', rating: 4, content: 'Good but not perfect.', user_id: '14', game_id: '2' },
  { id: '15', rating: 5, content: 'Best game ever played!', user_id: '15', game_id: '3' },
  { id: '16', rating: 4, content: 'Challenging puzzles.', user_id: '16', game_id: '3' },
  { id: '17', rating: 5, content: 'Игра просто фантастика!', user_id: '17', game_id: '4' },
  { id: '18', rating: 4, content: 'Fun for all ages.', user_id: '18', game_id: '4' },
  { id: '19', rating: 5, content: 'Masterpiece of gaming!', user_id: '19', game_id: '5' },
  { id: '20', rating: 4, content: 'Some minor issues.', user_id: '20', game_id: '5' },
  { id: '21', rating: 5, content: 'Awesome gameplay!', user_id: '21', game_id: '1' },
  { id: '22', rating: 3, content: 'It\'s just okay.', user_id: '22', game_id: '1' },
  { id: '23', rating: 5, content: 'Лучшая игра года!', user_id: '23', game_id: '2' },
  { id: '24', rating: 4, content: 'Good but not great.', user_id: '24', game_id: '2' },
  { id: '25', rating: 5, content: 'Best experience ever!', user_id: '25', game_id: '3' },
  { id: '26', rating: 4, content: 'Challenging and fun.', user_id: '26', game_id: '3' },
  { id: '27', rating: 5, content: 'Игра просто невероятна!', user_id: '27', game_id: '4' },
  { id: '28', rating: 4, content: 'Great for families.', user_id: '28', game_id: '4' },
  { id: '29', rating: 5, content: 'A must-play game!', user_id: '29', game_id: '5' },
  { id: '30', rating: 4, content: 'Some minor bugs.', user_id: '30', game_id: '5' },
  { id: '31', rating: 5, content: 'Love the story!', user_id: '31', game_id: '1' },
  { id: '32', rating: 3, content: 'Not my cup of tea.', user_id: '32', game_id: '1' },
  { id: '33', rating: 5, content: 'Очень крутая графика!', user_id: '33', game_id: '2' },
  { id: '34', rating: 4, content: 'Good but could improve.', user_id: '34', game_id: '2' },
  { id: '35', rating: 5, content: 'Best game I\'ve played!', user_id: '35', game_id: '3' },
  { id: '36', rating: 4, content: 'Challenging and rewarding.', user_id: '36', game_id: '3' },
  { id: '37', rating: 5, content: 'Игра просто идеальна!', user_id: '37', game_id: '4' },
  { id: '38', rating: 4, content: 'Fun and engaging.', user_id: '38', game_id: '4' },
  { id: '39', rating: 5, content: 'Masterpiece of gaming!', user_id: '39', game_id: '5' },
  { id: '40', rating: 4, content: 'Some minor issues.', user_id: '40', game_id: '5' },
  { id: '41', rating: 5, content: 'Awesome experience!', user_id: '21', game_id: '6' },
  { id: '42', rating: 4, content: 'Good but not perfect.', user_id: '22', game_id: '6' },
  { id: '43', rating: 5, content: 'Лучшая игра года!', user_id: '23', game_id: '7' },
  { id: '44', rating: 4, content: 'Challenging and fun.', user_id: '24', game_id: '7' },
  { id: '45', rating: 5, content: 'Best game ever played!', user_id: '25', game_id: '8' },
  { id: '46', rating: 4, content: 'Some minor bugs.', user_id: '26', game_id: '8' },
  { id: '47', rating: 5, content: 'Игра просто невероятна!', user_id: '27', game_id: '9' },
  { id: '48', rating: 4, content: 'Great for families.', user_id: '28', game_id: '9' },
  { id: '49', rating: 5, content: 'A must-play game!', user_id: '29', game_id: '10' },
  { id: '50', rating: 4, content: 'Some minor issues.', user_id: '30', game_id: '10' },
  { id: '51', rating: 5, content: 'Love the story!', user_id: '31', game_id: '1' },
  { id: '52', rating: 3, content: 'Not bad, but could be better.', user_id: '32', game_id: '1' },
  { id: '53', rating: 5, content: 'Очень крутая графика!', user_id: '33', game_id: '2' },
  { id: '54', rating: 4, content: 'Good but could improve.', user_id: '34', game_id: '2' },
  { id: '55', rating: 5, content: 'Best game I\'ve played!', user_id: '35', game_id: '3' },
  { id: '56', rating: 4, content: 'Challenging and rewarding.', user_id: '36', game_id: '3' },
  { id: '57', rating: 5, content: 'Игра просто идеальна!', user_id: '37', game_id: '4' },
  { id: '58', rating: 4, content: 'Fun and engaging.', user_id: '38', game_id: '4' },
  { id: '59', rating: 5, content: 'Masterpiece of gaming!', user_id: '39', game_id: '5' },
  { id: '60', rating: 4, content: 'Some minor issues.', user_id: '40', game_id: '5' },
  { id: '61', rating: 5, content: 'Awesome gameplay!', user_id: '41', game_id: '6' },
  { id: '62', rating: 3, content: 'It\'s just okay.', user_id: '42', game_id: '6' },
  { id: '63', rating: 5, content: 'Лучшая игра года!', user_id: '43', game_id: '7' },
  { id: '64', rating: 4, content: 'Good but not great.', user_id: '44', game_id: '7' },
  { id: '65', rating: 5, content: 'Best experience ever!', user_id: '45', game_id: '8' },
  { id: '66', rating: 4, content: 'Challenging and fun.', user_id: '46', game_id: '8' },
  { id: '67', rating: 5, content: 'Игра просто невероятна!', user_id: '47', game_id: '9' },
  { id: '68', rating: 4, content: 'Great for families.', user_id: '48', game_id: '9' },
  { id: '69', rating: 5, content: 'A must-play game!', user_id: '1', game_id: '10' },
  { id: '70', rating: 4, content: 'Some minor bugs.', user_id: '2', game_id: '10' },
  { id: '71', rating: 5, content: 'Love the graphics!', user_id: '3', game_id: '1' },
  { id: '72', rating: 3, content: 'Not my cup of tea.', user_id: '4', game_id: '1' },
  { id: '73', rating: 5, content: 'Очень крутая графика!', user_id: '5', game_id: '2' },
  { id: '74', rating: 4, content: 'Good but could improve.', user_id: '6', game_id: '2' },
  { id: '75', rating: 5, content: 'Best game I\'ve played!', user_id: '7', game_id: '3' },
  { id: '76', rating: 4, content: 'Challenging puzzles.', user_id: '8', game_id: '3' },
  { id: '77', rating: 5, content: 'Игра просто фантастика!', user_id: '9', game_id: '4' },
  { id: '78', rating: 4, content: 'Fun for all ages.', user_id: '10', game_id: '4' },
  { id: '79', rating: 5, content: 'Masterpiece of gaming!', user_id: '11', game_id: '5' },
  { id: '80', rating: 4, content: 'Some minor issues.', user_id: '12', game_id: '5' },
  { id: '81', rating: 5, content: 'Awesome experience!', user_id: '13', game_id: '6' },
  { id: '82', rating: 3, content: 'It\'s just okay.', user_id: '14', game_id: '6' },
  { id: '83', rating: 5, content: 'Лучшая игра года!', user_id: '15', game_id: '7' },
  { id: '84', rating: 4, content: 'Good but not great.', user_id: '16', game_id: '7' },
  { id: '85', rating: 5, content: 'Best game ever played!', user_id: '17', game_id: '8' },
  { id: '86', rating: 4, content: 'Challenging and fun.', user_id: '18', game_id: '8' },
  { id: '87', rating: 5, content: 'Игра просто невероятна!', user_id: '19', game_id: '9' },
  { id: '88', rating: 4, content: 'Great for families.', user_id: '20', game_id: '9' },
  { id: '89', rating: 5, content: 'A must-play game!', user_id: '21', game_id: '10' },
  { id: '90', rating: 4, content: 'Some minor bugs.', user_id: '22', game_id: '10' },
  { id: '91', rating: 5, content: 'Love the story!', user_id: '23', game_id: '1' },
  { id: '92', rating: 3, content: 'Not bad, but could be better.', user_id: '24', game_id: '1' },
  { id: '93', rating: 5, content: 'Очень крутая графика!', user_id: '25', game_id: '2' },
  { id: '94', rating: 4, content: 'Good but could improve.', user_id: '26', game_id: '2' },
  { id: '95', rating: 5, content: 'Best game I\'ve played!', user_id: '27', game_id: '3' },
  { id: '96', rating: 4, content: 'Challenging and rewarding.', user_id: '28', game_id: '3' },
  { id: '97', rating: 5, content: 'Игра просто идеальна!', user_id: '29', game_id: '4' },
  { id: '98', rating: 4, content: 'Fun and engaging.', user_id: '30', game_id: '4' },
  { id: '99', rating: 5, content: 'Masterpiece of gaming!', user_id: '31', game_id: '5' },
  { id: '100', rating: 4, content: 'Some minor issues.', user_id: '32', game_id: '5' },
];

export default { games, users, reviews }